/* Daily Cello · interface strings (en / de / pt) */
const UI = {
  brand_sub: ['your daily practice', 'dein tägliches Üben', 'o teu estudo diário'],
  nav_today: ['Today', 'Heute', 'Hoje'], nav_library: ['Library', 'Bibliothek', 'Biblioteca'], nav_piece: ['Piece', 'Stück', 'Peça'], nav_progress: ['Progress', 'Fortschritt', 'Progresso'],
  settings: ['Settings', 'Einstellungen', 'Definições'],
  hello_m: ['Good morning', 'Guten Morgen', 'Bom dia'], hello_a: ['Good afternoon', 'Guten Tag', 'Boa tarde'], hello_e: ['Good evening', 'Guten Abend', 'Boa noite'],
  todays_piece: ["Today's piece", 'Heutiges Stück', 'Peça de hoje'],
  change_piece: ['Change piece', 'Stück wechseln', 'Mudar de peça'],
  todays_practice: ["Today's practice", 'Heutiges Üben', 'Estudo de hoje'],
  chapter: ['Chapter', 'Kapitel', 'Capítulo'],
  length: ['Length', 'Dauer', 'Duração'], focus: ['Focus', 'Schwerpunkt', 'Foco'],
  f_balanced: ['Balanced', 'Ausgewogen', 'Equilibrado'], f_left: ['Left hand', 'Linke Hand', 'Mão esquerda'], f_bow: ['Bow & sound', 'Bogen & Klang', 'Arco & som'], f_music: ['Music & creativity', 'Musik & Kreativität', 'Música & criatividade'],
  begin: ['Begin', 'Beginnen', 'Começar'], new_mix: ['New mix', 'Neu mischen', 'Nova mistura'],
  min: ['min', 'Min.', 'min'], exercises: ['exercises', 'Übungen', 'exercícios'], total: ['total', 'gesamt', 'total'],
  bars: ['bars', 'Takte', 'compassos'], bar: ['bar', 'Takt', 'compasso'],
  key: ['Key', 'Tonart', 'Tonalidade'], time: ['Time', 'Takt', 'Compasso'], tempo: ['Tempo', 'Tempo', 'Andamento'],
  how: ['How to do it', 'So geht es', 'Como fazer'], why_more: ['Why', 'Warum', 'Porquê'],
  check: ['Check', 'Kontrolle', 'Verifica'],
  listen: ['Listen', 'Anhören', 'Ouvir'], stop: ['Stop', 'Stopp', 'Parar'],
  metronome: ['Metronome', 'Metronom', 'Metrónomo'], tuner: ['Tuner', 'Stimmgerät', 'Afinador'], drone: ['Drone', 'Bordun', 'Bordão'], timer: ['Timer', 'Timer', 'Temporizador'],
  play: ['Play-along', 'Begleitung', 'Acompanhamento'], notes: ['Notes', 'Notizen', 'Notas'], fingers: ['Fingers', 'Finger', 'Dedos'],
  finger_edit_hint: ['Tap a note, then choose its finger.', 'Tippe eine Note an und wähle den Finger.', 'Toca numa nota e escolhe o dedo.'],
  finger_saved: ['Fingering saved', 'Fingersatz gespeichert', 'Dedilhação guardada'],
  remove: ['Remove', 'Entfernen', 'Remover'],
  how_go: ['How did it go?', 'Wie lief es?', 'Como correu?'], hard: ['Hard', 'Schwer', 'Difícil'], okay: ['OK', 'Geht so', 'Razoável'], easy: ['Easy', 'Leicht', 'Fácil'],
  back: ['Back', 'Zurück', 'Anterior'], next: ['Next', 'Weiter', 'Seguinte'], finish: ['Finish', 'Beenden', 'Terminar'], close: ['Close', 'Schließen', 'Fechar'], continue: ['Continue', 'Weiter', 'Continuar'],
  page_of: ['{a} / {b}', '{a} / {b}', '{a} / {b}'],
  done_title: ['Well played', 'Gut gespielt', 'Bem tocado'], done_body: ['{n} exercises in {m} minutes. Your ratings shape the next session.', '{n} Übungen in {m} Minuten. Deine Bewertungen formen die nächste Einheit.', '{n} exercícios em {m} minutos. As tuas avaliações moldam a próxima sessão.'],
  back_home: ['Back to Today', 'Zurück zu Heute', 'Voltar a Hoje'],
  round: ['Round', 'Runde', 'Volta'], faster: ['Faster', 'Schneller', 'Mais rápido'], slower: ['Slower', 'Langsamer', 'Mais lento'], goal: ['goal', 'Ziel', 'objetivo'], last_time: ['last time', 'letztes Mal', 'da última vez'],
  clicks: ['Clicks per beat', 'Klicks pro Schlag', 'Cliques por tempo'], beats: ['Beats', 'Schläge', 'Tempos'],
  start: ['Start', 'Start', 'Iniciar'], pause: ['Pause', 'Pause', 'Pausa'], reset: ['Reset', 'Zurücksetzen', 'Repor'],
  start_mic: ['Listen', 'Zuhören', 'Ouvir'], stop_mic: ['Stop listening', 'Zuhören beenden', 'Parar de ouvir'], play_target: ['Play target', 'Zielton', 'Ouvir alvo'],
  hold_hint: ['Hold each note in the green zone for {s} s.', 'Halte jeden Ton {s} s in der grünen Zone.', 'Mantém cada nota na zona verde durante {s} s.'],
  all_green: ['All notes green.', 'Alle Töne grün.', 'Todas as notas verdes.'], again: ['Again', 'Nochmal', 'Outra vez'], play_note: ['Play a note…', 'Spiel einen Ton…', 'Toca uma nota…'],
  wrong_note: ['You are on {n}. Target: {t}.', 'Du spielst {n}. Ziel: {t}.', 'Estás em {n}. Alvo: {t}.'],
  mic_blocked: ['The microphone is not available here. Press "Play target", sing it and match it by ear.', 'Das Mikrofon ist hier nicht verfügbar. Drücke „Zielton", singe ihn und triff ihn mit dem Ohr.', 'O microfone não está disponível aqui. Carrega em "Ouvir alvo", canta e acerta de ouvido.'],
  mic_denied: ['Microphone access is off. Turn it on in iPad Settings → Daily Cello → Microphone.', 'Mikrofonzugriff ist aus. In iPad-Einstellungen → Daily Cello → Mikrofon einschalten.', 'O acesso ao microfone está desligado. Liga-o em Definições do iPad → Daily Cello → Microfone.'],
  headphones: ['With drone or play-along on, headphones help the tuner hear only your cello.', 'Mit Bordun oder Begleitung helfen Kopfhörer, damit das Stimmgerät nur dein Cello hört.', 'Com bordão ou acompanhamento, auscultadores ajudam o afinador a ouvir só o violoncelo.'],
  cents: ['cents', 'Cent', 'cents'], guide: ['Cello guide', 'Cello-Führung', 'Guia de violoncelo'], water: ['Piano', 'Klavier', 'Piano'], loop: ['Loop', 'Schleife', 'Repetir'],
  bars_ab: ['Bars {a}–{b}', 'Takte {a}–{b}', 'Compassos {a}–{b}'], bar_n: ['Bar {n}', 'Takt {n}', 'Compasso {n}'],
  volume: ['Volume', 'Lautstärke', 'Volume'], switch_to: ['Switch to', 'Wechseln zu', 'Mudar para'],
  notes_ph: ['Your fingerings, bowings, ideas…', 'Deine Fingersätze, Striche, Ideen…', 'As tuas dedilhações, arcadas, ideias…'],
  reflect_ph: ['Today it sounded good when… · Tomorrow I want to…', 'Heute klang es gut, als… · Morgen möchte ich…', 'Hoje soou bem quando… · Amanhã quero…'],
  based_on: ['After', 'Nach', 'Segundo'],
  // library / import
  library_h: ['Your pieces', 'Deine Stücke', 'As tuas peças'], add_piece: ['Add a piece', 'Stück hinzufügen', 'Adicionar peça'],
  add_hint: ['MusicXML (.mxl, .musicxml) from Claude, MuseScore or a scanning app. PDFs and photos are read with your Claude key.', 'MusicXML (.mxl, .musicxml) von Claude, MuseScore oder einer Scan-App. PDFs und Fotos werden mit deinem Claude-Schlüssel gelesen.', 'MusicXML (.mxl, .musicxml) do Claude, MuseScore ou de uma app de digitalização. PDFs e fotos são lidos com a tua chave Claude.'],
  importing: ['Reading the score…', 'Noten werden gelesen…', 'A ler a partitura…'],
  imported: ['Added: {t} · {n} exercises', 'Hinzugefügt: {t} · {n} Übungen', 'Adicionada: {t} · {n} exercícios'],
  import_fail: ['Could not read this file: {e}', 'Datei konnte nicht gelesen werden: {e}', 'Não foi possível ler o ficheiro: {e}'],
  pdf_needs: ['To turn a PDF or photo into a piece, send it to Claude in the chat and open the .mxl you get back here. Or add your Claude API key in Settings so the app can read it directly.', 'Um ein PDF oder Foto in ein Stück zu verwandeln, schick es Claude im Chat und öffne die .mxl hier. Oder trage deinen Claude-API-Schlüssel in den Einstellungen ein.', 'Para transformar um PDF ou foto numa peça, envia-o ao Claude no chat e abre aqui o .mxl. Ou adiciona a tua chave da API Claude nas Definições.'],
  open_piece: ['Open', 'Öffnen', 'Abrir'], delete_piece: ['Delete', 'Löschen', 'Apagar'], sure: ['Tap again to delete', 'Nochmal tippen zum Löschen', 'Toca outra vez para apagar'],
  built_in: ['Built in', 'Eingebaut', 'Incluída'], practise: ['Practise', 'Üben', 'Estudar'], practise_spot: ['Practise this spot', 'Diese Stelle üben', 'Estudar esta passagem'],
  spots_h: ['Difficult spots', 'Schwierige Stellen', 'Passagens difíceis'], sections: ['Sections', 'Teile', 'Secções'], not_yet: ['not practised yet', 'noch nicht geübt', 'ainda não estudada'],
  all_spots: ['All', 'Alle', 'Todas'],
  // progress
  progress_h: ['Your journey', 'Dein Weg', 'O teu percurso'], st_sessions: ['sessions', 'Einheiten', 'sessões'], st_minutes: ['minutes', 'Minuten', 'minutos'], st_streak: ['days in a row', 'Tage in Folge', 'dias seguidos'], st_week: ['minutes this week', 'Minuten diese Woche', 'minutos esta semana'],
  history: ['History', 'Verlauf', 'Histórico'], no_hist: ['No sessions yet. Your first one starts on Today.', 'Noch keine Einheiten. Die erste startest du unter Heute.', 'Ainda não há sessões. A primeira começa em Hoje.'],
  your_notes: ['Your notes', 'Deine Notizen', 'As tuas notas'],
  // settings
  set_lang: ['Language', 'Sprache', 'Idioma'], set_theme: ['Look', 'Darstellung', 'Aspeto'], th_light: ['Light', 'Hell', 'Claro'], th_dark: ['Dark', 'Dunkel', 'Escuro'],
  set_a4: ['Reference pitch A4', 'Kammerton A4', 'Lá de referência'], set_tol: ['Green zone', 'Grüne Zone', 'Zona verde'], set_hold: ['Hold time', 'Haltezeit', 'Tempo a manter'],
  set_drone: ['Drone sound', 'Bordunklang', 'Som do bordão'], tone_cello: ['Cello-like', 'Celloartig', 'Tipo violoncelo'], tone_organ: ['Organ', 'Orgel', 'Órgão'],
  set_fing: ['Finger numbers', 'Fingersatz', 'Dedilhação'], fing_all: ['On every note', 'Auf jeder Note', 'Em cada nota'], fing_off: ['Hidden', 'Ausgeblendet', 'Escondida'],
  set_key: ['Claude API key (optional)', 'Claude-API-Schlüssel (optional)', 'Chave da API Claude (opcional)'],
  key_hint: ['Lets the app read PDFs and photos itself. Each score costs a few cents on your Anthropic account. Without a key, send scores to Claude in the chat.', 'Damit liest die App PDFs und Fotos selbst. Jede Partitur kostet ein paar Rappen auf deinem Anthropic-Konto. Ohne Schlüssel: Partituren im Chat an Claude schicken.', 'Permite à app ler PDFs e fotos. Cada partitura custa alguns cêntimos na tua conta Anthropic. Sem chave, envia as partituras ao Claude no chat.'],
  profile_h: ['Profile', 'Profil', 'Perfil'], edit_answers: ['Change my answers', 'Antworten ändern', 'Alterar respostas'], add_student: ['Add a student', 'Schüler·in hinzufügen', 'Adicionar aluno'], switch_profile: ['Who is practising?', 'Wer übt?', 'Quem está a estudar?'],
  reset_prog: ['Delete this profile\'s progress', 'Fortschritt dieses Profils löschen', 'Apagar o progresso deste perfil'], deleted: ['Deleted', 'Gelöscht', 'Apagado'], done: ['Done', 'Fertig', 'Feito'],
  credits: ['Photos: Wikimedia Commons. Score: Saint-Saëns, Durand edition (public domain).', 'Fotos: Wikimedia Commons. Noten: Saint-Saëns, Ausgabe Durand (gemeinfrei).', 'Fotos: Wikimedia Commons. Partitura: Saint-Saëns, edição Durand (domínio público).'],
  // onboarding
  ob_welcome: ['Welcome to Daily Cello', 'Willkommen bei Daily Cello', 'Bem-vindo ao Daily Cello'],
  ob_welcome_sub: ['A few questions, so every exercise fits you.', 'Ein paar Fragen, damit jede Übung zu dir passt.', 'Algumas perguntas, para que cada exercício seja para ti.'],
  ob_name: ['What is your name?', 'Wie heißt du?', 'Como te chamas?'],
  ob_role: ['Who will use Daily Cello?', 'Wer benutzt Daily Cello?', 'Quem vai usar o Daily Cello?'],
  r_student: ['I practise myself', 'Ich übe selbst', 'Eu estudo'], r_teacher: ['I teach students', 'Ich unterrichte', 'Eu dou aulas'], r_both: ['Both', 'Beides', 'Os dois'],
  ob_age: ['Who is practising?', 'Wer übt?', 'Quem estuda?'], a_child: ['A child (up to 12)', 'Ein Kind (bis 12)', 'Uma criança (até 12)'], a_teen: ['A teenager', 'Ein Teenager', 'Um adolescente'], a_adult: ['An adult', 'Ein Erwachsener', 'Um adulto'],
  ob_years: ['How long have you played the cello?', 'Wie lange spielst du schon Cello?', 'Há quanto tempo tocas violoncelo?'],
  y0: ['Less than a year', 'Weniger als ein Jahr', 'Menos de um ano'], y1: ['1–3 years', '1–3 Jahre', '1–3 anos'], y3: ['3–6 years', '3–6 Jahre', '3–6 anos'], y6: ['More than 6 years', 'Mehr als 6 Jahre', 'Mais de 6 anos'], ypro: ['Professional / student of music', 'Profi / Musikstudium', 'Profissional / estudante de música'],
  ob_pos: ['Where on the fingerboard are you at home?', 'Wo auf dem Griffbrett fühlst du dich zu Hause?', 'Onde na escala te sentes em casa?'],
  p_first: ['1st position', '1. Lage', '1.ª posição'], p_fourth: ['Up to 4th position', 'Bis zur 4. Lage', 'Até à 4.ª posição'], p_neck: ['All neck positions', 'Alle Halslagen', 'Todas as posições do braço'], p_thumb: ['Thumb position too', 'Auch Daumenlage', 'Também posição de polegar'],
  ob_clefs: ['Which clefs can you read?', 'Welche Schlüssel kannst du lesen?', 'Que claves sabes ler?'],
  c_bass: ['Bass clef', 'Bassschlüssel', 'Clave de fá'], c_tenor: ['Tenor clef', 'Tenorschlüssel', 'Clave de dó (tenor)'], c_treble: ['Treble clef', 'Violinschlüssel', 'Clave de sol'],
  ob_improve: ['What do you want to get better at?', 'Was möchtest du verbessern?', 'O que queres melhorar?'],
  i_intonation: ['Intonation', 'Intonation', 'Afinação'], i_shift: ['Shifting', 'Lagenwechsel', 'Mudanças de posição'], i_bow: ['Bow & sound', 'Bogen & Klang', 'Arco & som'], i_vibrato: ['Vibrato', 'Vibrato', 'Vibrato'], i_rhythm: ['Rhythm & reading', 'Rhythmus & Lesen', 'Ritmo & leitura'], i_musical: ['Expression', 'Ausdruck', 'Expressão'], i_creative: ['Creativity', 'Kreativität', 'Criatividade'],
  ob_time: ['How long do you usually practise?', 'Wie lange übst du meistens?', 'Quanto tempo costumas estudar?'],
  ob_ready: ['All set, {n}.', 'Alles bereit, {n}.', 'Está tudo pronto, {n}.'], ob_ready_sub: ['You can change these answers any time in Settings.', 'Du kannst die Antworten jederzeit in den Einstellungen ändern.', 'Podes mudar as respostas a qualquer momento nas Definições.'],
  ob_start: ['Start practising', 'Mit dem Üben beginnen', 'Começar a estudar'], skip: ['Skip', 'Überspringen', 'Saltar'],
  choose_many: ['Choose all that fit', 'Wähle alles, was passt', 'Escolhe tudo o que se aplica'],
  student_name: ['Student\'s name', 'Name der Schülerin / des Schülers', 'Nome do aluno'],
  suggested: ['suggested fingering · tap Fingers to change', 'Fingersatz-Vorschlag · mit Finger ändern', 'dedilhação sugerida · muda em Dedos']
};
